name: Close Issues from Non-Collaborators

on:
  issues:
    types: [opened]

jobs:
  close-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue author and close if not collaborator
        uses: actions/github-script@v6
        with:
          script: |
            const issueCreator = context.payload.issue.user.login;
            const allowedUsers = ['Limkon']; // 允许的用户列表
            if (!allowedUsers.includes(issueCreator)) {
              github.issues.update({
                ...context.issue,
                state: 'closed'
              });
              github.issues.createComment({
                ...context.issue,
                body: `Sorry @${issueCreator}, only authorized users can create issues in this repository.`
              });
            }
