name: Delete Closed Issues

on:
  workflow_dispatch:

jobs:
  delete-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: |
         chmod +x delete-closed-issues.sh
         ./delete-closed-issues.sh
