name: Delete Closed Issues

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  delete-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Prepare and run script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          #!/bin/bash

          # 设置 GitHub 个人访问令牌和仓库信息
          GITHUB_TOKEN="${GITHUB_TOKEN}"
          REPO_OWNER="Limkon"   # 仓库所有者
          REPO_NAME="bookmarks" # 仓库名称

          PAGE=1
          PER_PAGE=100

          # GraphQL 查询模板
          QUERY=$(cat <<EOF
          {
            repository(owner: "$REPO_OWNER", name: "$REPO_NAME") {
              issues(states: CLOSED, first: 100, after: "$AFTER_CURSOR") {
                edges {
                  node {
                    id
                  }
                }
                pageInfo {
                  hasNextPage
                  endCursor
                }
              }
            }
          }
          EOF
          )

          # GraphQL Mutation 模板
          MUTATION=$(cat <<EOF
          mutation {
            deleteIssue(input: {issueId: "ID"}) {
              clientMutationId
            }
          }
          EOF
          )

          while : ; do
            # 执行 GraphQL 查询以获取关闭的 Issues
            RESPONSE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -X POST -d "{\"query\": \"${QUERY//\"/\\\"}\"}" \
              "https://api.github.com/graphql")

            # 打印 API 响应以便调试
            
