name: Delete All Issues

on:
  workflow_dispatch:

jobs:
  delete_issues:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete All Issues
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      run: |
        #!/bin/bash

        # 设置仓库所有者和名称
        REPO_OWNER="Limkon"
        REPO_NAME="bookmarks"

        # GitHub API 令牌
        GITHUB_TOKEN="${MY_GITHUB_TOKEN}"

        # GitHub API 端点
        API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues"

        # 获取所有的 Issue（包括开放和关闭）
        echo "Fetching all issues..."
        response=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "${API_URL}?state=all")
        echo "API response:"
        echo "$response"

        issues=$(echo "$response" | jq -r '.[].number')

        if [ -z "$issues" ]; then
          echo "No issues found."
        else
          # 遍历所有的 Issue 并删除
          for issue_number in $issues; do
            echo "Deleting Issue #${issue_number}"
            issue_url="${API_URL}/${issue_number}"
            response=$(curl -s -D - -o /dev/null -w "%{http_code}" -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" "${issue_url}")
            if [ "$response" -eq 204 ]; then
              echo "Issue #${issue_number} deleted successfully."
            elif [ "$response" -eq 404 ]; then
              echo "Issue #${issue_number} not found (404). It might have already been deleted."
            else
              echo "Failed to delete Issue #${issue_number}. Response code: ${response}"
            fi
          done
        fi

        echo "All Issues have been processed."
