name: Delete All Issues

on:
  workflow_dispatch:

jobs:
  delete_issues:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Delete All Issues
      run: |
        #!/bin/bash

        # 设置仓库所有者和名称
        REPO_OWNER="Limkon"
        REPO_NAME="bookmarks"

        # GitHub API 令牌
        GITHUB_TOKEN="${{ secrets.MY_GITHUB_TOKEN }}"

        # GitHub API 端点
        API_URL="https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/issues"

        # 获取所有开放的 Issue
        issues=$(curl -s -H "Authorization: token ${GITHUB_TOKEN}" "${API_URL}?state=open" | jq -r '.[].number')

        # 遍历所有的 Issue 并删除
        for issue_number in $issues; do
          echo "Deleting Issue #${issue_number}"
          curl -s -X DELETE -H "Authorization: token ${GITHUB_TOKEN}" "${API_URL}/${issue_number}"
        done

        echo "All Issues have been deleted."
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
