name: Delete Closed Issues

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  delete-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Prepare script
        run: |
          # 将脚本内容添加到工作目录中
          cat << 'EOF' > delete-closed-issues.sh
#!/bin/bash

# 设置 GitHub 个人访问令牌和仓库信息
GITHUB_TOKEN="${GITHUB_TOKEN}"
REPO="Limkon/bookmarks"  # 格式为 "owner/repo"

PAGE=1
PER_PAGE=100

while : ; do
  # 获取当前页的关闭 Issues
  ISSUES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    "https://api.github.com/repos/$REPO/issues?state=closed&per_page=$PER_PAGE&page=$PAGE" \
    | jq -r '.[].number')

  # 如果没有更多的 Issue，则退出循环
  if [ -z "$ISSUES" ]; then
    break
  fi

  # 批量删除每个关闭的 Issue
  for ISSUE in $ISSUES; do
    echo "Deleting Issue #$ISSUE"
    curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
      "https://api.github.com/repos/$REPO/issues/$ISSUE"
  done

  PAGE=$((PAGE + 1))
done

echo "Finished deleting closed issues."
EOF
          chmod +x delete-closed-issues.sh

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # 使用新名称的 Secret
        run: ./delete-closed-issues.sh
