name: Delete Closed Issues

on:
  workflow_dispatch:

jobs:
  delete-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get install -y jq curl

      - name: Prepare script
        run: |
          echo '#!/bin/bash' > delete-closed-issues.sh
          echo 'echo "Hello World"' >> delete-closed-issues.sh
          chmod +x delete-closed-issues.sh

      - name: Run script
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        run: ./delete-closed-issues.sh
