name: Update links.json from Issue

on:
  issues:
    types: [opened]

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Issue details
        id: issue
        uses: actions/github-script@v6
        with:
          script: |
            const title = context.payload.issue.title.toLowerCase();
            const body = context.payload.issue.body.trim();
            return { title, body };

      - name: Debug Issue title and body
        run: |
          echo "Issue title: '${{ steps.issue.outputs.title }}'"
          echo "Issue body: '${{ steps.issue.outputs.body }}'"

      - name: Update links.json
        id: update_links
        run: |
          echo "Fetching links.json..."
          links_file="links.json"

          # Load current links.json content
          if [ ! -f "$links_file" ]; then
            echo "links.json does not exist. Creating a new one."
            echo "[]" > $links_file
          fi

          # Parse Issue data
          TITLE="${{ steps.issue.outputs.title }}"
          BODY="${{ steps.issue.outputs.body }}"

          if [[ "$TITLE" == "add" ]]; then
            # Replace all Chinese commas with English commas and split by comma
            BODY=$(echo $BODY | sed 's/，/,/g')
            NAME=$(echo $BODY | cut -d',' -f1)
            URL=$(echo $BODY | cut -d',' -f2)

            echo "Adding link: $NAME ($URL)"
            
            # Append the new link to the links.json
            jq --arg name "$NAME" --arg url "$URL" '. += [{"name": $name, "url": $url}]' $links_file > tmp.$$.json && mv tmp.$$.json $links_file

          elif [[ "$TITLE" == "del" ]]; then
            NAME=$BODY

            echo "Deleting link: $NAME"

            # Remove the link with the specified name from links.json
            jq --arg name "$NAME" 'del(.[] | select(.name == $name))' $links_file > tmp.$$.json && mv tmp.$$.json $links_file
          else
            echo "Invalid Issue title. Please use 'add' or 'del'."
            exit 1
          fi

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add links.json
          git commit -m "Updated links.json from Issue #${{ github.event.issue.number }}"
          git push

      - name: Close Issue
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"state":"closed"}' \
            "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
