name: update-links

on:
  issues:
    types: [opened]

jobs:
  update-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      
      - name: Process issue
        uses: actions/github-script@v6
        id: process_issue
        with:
          script: |
            const issueTitle = context.payload.issue.title.trim();
            const issueBody = context.payload.issue.body.trim();
            
            // 检查标题是否为 'add' 或 'del'
            if (issueTitle !== 'add' && issueTitle !== 'del') {
              core.setFailed('Invalid Issue title. Please use "add" or "del".');
              return;
            }
            
            // 处理 'add' 情况
            if (issueTitle === 'add') {
              const [name, url] = issueBody.split(',').map(item => item.trim());
              
              // 自动补齐网址
              let formattedUrl = url;
              if (!/^https?:\/\//i.test(url)) {
                formattedUrl = `https://${url}`;
              }
              
              // 打印调试信息
              console.log(`Adding link: Name = ${name}, URL = ${formattedUrl}`);
              
              // 读取 links.json 文件
              const fs = require('fs');
              const path = './links.json';
              let links = [];

              if (fs.existsSync(path)) {
                links = JSON.parse(fs.readFileSync(path, 'utf-8'));
              }
              
              // 添加新链接
              links.push({ name, url: formattedUrl });
              
              // 保存更新后的 links.json 文件
              fs.writeFileSync(path, JSON.stringify(links, null, 2));
              console.log('Link added successfully!');
            }
            
            // 处理 'del' 情况
            if (issueTitle === 'del') {
              const urlToDelete = issueBody.trim();
              
              // 读取 links.json 文件
              const fs = require('fs');
              const path = './links.json';
              let links = [];

              if (fs.existsSync(path)) {
                links = JSON.parse(fs.readFileSync(path, 'utf-8'));
              }
              
              // 过滤掉要删除的链接
              const newLinks = links.filter(link => link.url !== urlToDelete);
              
              // 保存更新后的 links.json 文件
              fs.writeFileSync(path, JSON.stringify(newLinks, null, 2));
              console.log('Link deleted successfully!');
            }
          
      - name: Commit changes
        if: steps.process_issue.conclusion == 'success'
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add links.json
          git commit -m "Update links.json"
          git push

      - name: Close issue
        if: steps.process_issue.conclusion == 'success'
        uses: actions-ecosystem/action-close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
